server:
  port: 10101

spring:
  application:
    name: springboot-rabbitmq
  redis:
    host: 192.168.1.150
    port: 6379
    password:
    timeout: 5000000
    lettuce:
      pool:
        # 链接池中最小的空闲链接 默认为0
        min-idle: 0
        # 链接池中最大的空闲连接 默认为 8
        max-idle: 8
        #连接池中最大数据库链接数 默认为8
        max-active: 8
        #连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms


  rabbitmq:
    host: 192.168.1.150
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    listener:
      simple:
        acknowledge-mode: manual
#    publisher-confirm-type: correlated

logging:
  level:
    root: debug