server:
  port: 8081

spring:
  application:
    name: sharding-redis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.150:3308/monomer_order?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.150
    port: 6379
    password:
    timeout: 5000000
    lettuce:
      pool:
        max-active: -1
        max-wait: 1
        max-idle: 1000
        min-idle: 1000
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

mybatis-plus:
  #  扫描依赖的jar包下的所有mapper.xml
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

