package me.zeanzai.rbac.mapper;

import me.zeanzai.rbac.entity.SysUserToken;
import me.zeanzai.rbac.entity.SysUserTokenExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SysUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    long countByExample(SysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int deleteByExample(SysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int insert(SysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int insertSelective(SysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    List<SysUserToken> selectByExample(SysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    SysUserToken selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int updateByExampleSelective(@Param("record") SysUserToken record, @Param("example") SysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int updateByExample(@Param("record") SysUserToken record, @Param("example") SysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int updateByPrimaryKeySelective(SysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbg.generated Sat May 28 21:51:44 CST 2022
     */
    int updateByPrimaryKey(SysUserToken record);
}