server:
  port: 9001
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/xiaobai_up?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false'
    username: root
    password: root1003
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5793931c-ffab-42bf-ae52-c430974085c3
mybatis:
  type-aliases-package: me.zeanzai.rbac.entity
  mapper-locations: classpath:mybatis/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'