package zeanzai.me.member.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zeanzai.me.member.entity.Vehicle;
import zeanzai.me.member.entity.VehicleExample;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    long countByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int deleteByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int insertSelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    List<Vehicle> selectByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    Vehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int updateByExampleSelective(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int updateByExample(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int updateByPrimaryKeySelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Thu May 26 23:17:38 CST 2022
     */
    int updateByPrimaryKey(Vehicle record);
}