server:
  port: 8080


spring:
  application:
    name: sharding-shphere-ds
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.150:3307/monomer_order?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: debug