server:
  port: 8080

spring:
  application:
    name: sharding-sql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/monomer_order?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
#    root: debug
    me.zeanzai: debug
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #  扫描依赖的jar包下的所有mapper.xml
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#logging:
##  file:
##    path: ./logs
#  level:
#    root: debug

#
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl