# 端口号
server:
  port: 10001

spring:
  application:
    # 注册到nacos上的服务名称，也是服务发现的名称，必写
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        # nacos的注册地址
        server-addr: 192.168.56.10:8848
        # nacos-as-register
        namespace: 616abb81-03c5-4fdb-aa0b-f7138144c1cb
#    sentinel:
#      transport:
#        dashboard: 192.168.56.10:8858
#      datasource:
#        flowcontroll:
#          nacos:
#            server-addr: 192.168.1.1.150:8848
#            data-id: ${spring.application.name}-flowcontroll
#            group-id:
#            data-type: json
#            rule-type: flow
#        degradecontroll:
#          nacos:
#            server-addr: 192.168.1.1.150:8848
#            data-id: ${spring.application.name}-flowcontroll
#            group-id:
#            data-type: json
#            rule-type: degrade

management:
  endpoints:
    web:
      exposure:
        # yml文件中存在特殊字符，必须用单引号包含，否则启动报错
        include: '*'
