server:
  port: 8082

spring:
  application:
    name: sharding-datasource
  datasource:

    ## master 只有一个，所以这里应该是一个map，而不是list，在 DataSourceConfig 中，master也只是一个map，而非一个list
    masters:
      username: root
      password: root
      url: jdbc:mysql://192.168.1.150:3307/monomer_order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      #        driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    ## slaves 是一个list
    slaves:
      - username: root
        password: root
        url: jdbc:mysql://192.168.1.150:3308/monomer_order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.1.150
    port: 6379
    password:
#    timeout: 100
#    lettuce:
#      pool:
#        max-active: -1
#        max-wait: 1
#        max-idle: 1000
#        min-idle: 1000

mybatis-plus:
  #  扫描依赖的jar包下的所有mapper.xml
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


